### ISSUE TITLE
SecureSocketProtocol

### ISSUE THREAD

**Issue by gotoel** [ImVexed/NotALicensingPlatform#1]
Hello, 

I was just wondering. Since this doesn't use the SSP3 lib like LiteCode does that mean this is less secure than LiteCode? Or is the same type of security implemented here? Or could it be implemented fairly easily?

I'm trying to find a platform for securing my software and need to choose between NALP or LiteCode so any help regarding this choice would be appreciated, thanks.

**Comment by ImVexed** [comment]
Both are open source and I would recommend manually going through both and comparing the security of both. Lately, I believe dragon hunter has removed the Mazing handshake by default from LiteCode, and if I remember correctly it now uses an RSA handshake or none at all I'm not quite sure. Both have their strong points, SSP3 and LC mainly being that they're highly configurable and are very well made with lots of testing. The purpose of this project is mainly to make a more lightweight version of LiteCode that does not have external dependencies, and for the most part, can be contained in one class. I've achieved this goal, but this is not intended to rival what LC is, only an alternative if one cannot afford to include all the internals or needs a more lightweight version for whatever reason. Both are viable choices, but in my opinion, NaLP is much easier to hack up to your liking, where doing so with LiteCode or SSP3 may lead to unforeseen consequences hidden in its complexity. Your answer will most likely derive from what your program demands, and which platform can fulfill those requirements.

**Comment by gotoel** [comment]
Thank you for the in-depth answer. Since I asked the question I already managed to hack up NaLP to my liking and it's cooperating perfectly!

Thanks again for the great project and explanation.
